from enum import IntEnum

APP_NAME = "mcp-project-updater"
DEFAULT_ENCODING = "utf-8"
DEFAULT_SMOKE_PROFILE = "dev"
REPORT_FILE_NAME = "Report.txt"
REPORT_DIAGNOSTICS_FILE_NAME = "report-diagnostics.json"
REPORT_STATS_FILE_NAME = "report-stats.json"
REPORT_ROOT_REGEX = r"^\s*-\s*Конфигурации\."


class ExitCode(IntEnum):
    SUCCESS = 0
    SUCCESS_WITH_WARNINGS = 1
    CONFIG_ERROR = 2
    GIT_REPOSITORY_NOT_FOUND = 3
    GIT_TRACKED_CHANGES = 4
    GIT_PULL_FAILED = 5
    MISSING_SOURCES = 6
    MAIN_CONFIG_REQUIRED_MISSING = 7
    EXTENSION_REQUIRED_MISSING = 8
    PARSER_FAILED = 9
    REPORT_VALIDATION_FAILED = 10
    DOCKER_UNAVAILABLE = 11
    BUILD_CONTAINER_FAILED = 12
    BUILD_SMOKE_FAILED = 13
    PRODUCTION_SWITCH_FAILED = 14
    PRODUCTION_SMOKE_FAILED = 15
    ROLLBACK_FAILED = 16
    LOCK_ALREADY_EXISTS = 17
    MISSING_REQUIRED_SECRET = 18
    INVALID_STATE = 19
    NOTIFICATION_FAILED = 20
