from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

from .config import ConfigValidationError, ProjectConfig, load_project_config


DEFAULT_CLIENT_HOST = "1c-mcp"
DEFAULT_CODEX_OUTPUT_NAME = "codex-mcp-servers.toml"
DEFAULT_CURSOR_OUTPUT_NAME = "cursor-mcp.json"
SERVER_NAME_PREFIX = "1c-code-metadata-mcp"


@dataclass(frozen=True, slots=True)
class MCPClientServer:
    project: str
    server_name: str
    url: str
    config_path: Path


@dataclass(frozen=True, slots=True)
class MCPClientConfigGenerationResult:
    servers: list[MCPClientServer]
    warnings: list[str]
    codex_output_path: Path
    cursor_output_path: Path


def generate_mcp_client_configs(
    data_root: Path,
    output_dir: Path,
    *,
    client_host: str | None = DEFAULT_CLIENT_HOST,
) -> MCPClientConfigGenerationResult:
    servers, warnings = collect_mcp_client_servers(data_root, client_host=client_host)
    output_dir.mkdir(parents=True, exist_ok=True)
    codex_output_path = output_dir / DEFAULT_CODEX_OUTPUT_NAME
    cursor_output_path = output_dir / DEFAULT_CURSOR_OUTPUT_NAME
    codex_output_path.write_text(render_codex_toml(servers), encoding="utf-8")
    cursor_output_path.write_text(render_cursor_json(servers), encoding="utf-8")
    return MCPClientConfigGenerationResult(
        servers=servers,
        warnings=warnings,
        codex_output_path=codex_output_path,
        cursor_output_path=cursor_output_path,
    )


def collect_mcp_client_servers(
    data_root: Path,
    *,
    client_host: str | None = DEFAULT_CLIENT_HOST,
) -> tuple[list[MCPClientServer], list[str]]:
    if not data_root.exists():
        raise FileNotFoundError(f"Data root does not exist: {data_root}")
    if not data_root.is_dir():
        raise NotADirectoryError(f"Data root is not a directory: {data_root}")

    configs = sorted(path for path in data_root.iterdir() if path.is_dir() and (path / "project.json").exists())
    loaded: list[ProjectConfig] = []
    warnings: list[str] = []
    for project_config_path in configs:
        config_path = project_config_path / "project.json"
        try:
            loaded.append(load_project_config(config_path))
        except (ConfigValidationError, OSError, ValueError) as exc:
            warnings.append(f"{config_path}: {exc}")

    base_names = [_server_name_for_project(config.project) for config in loaded]
    server_names = _dedupe_names(base_names)
    servers = [
        MCPClientServer(
            project=config.project,
            server_name=server_name,
            url=client_url(config.mcp.production.url, client_host=client_host),
            config_path=config.config_path,
        )
        for config, server_name in zip(loaded, server_names, strict=True)
    ]
    return servers, warnings


def client_url(production_url: str, *, client_host: str | None) -> str:
    if not client_host:
        return production_url
    parts = urlsplit(production_url)
    if not parts.hostname:
        return production_url
    netloc = client_host
    if parts.port is not None:
        netloc = f"{netloc}:{parts.port}"
    return urlunsplit((parts.scheme, netloc, parts.path, parts.query, parts.fragment))


def render_codex_toml(servers: list[MCPClientServer]) -> str:
    lines = [
        "# Generated by generate_mcp_client_configs.py.",
        "# Paste these sections into Codex config.toml or include them in your profile.",
        "",
    ]
    for server in servers:
        lines.extend(
            [
                f"[mcp_servers.{server.server_name}]",
                "enabled = true",
                f'url = "{_toml_escape(server.url)}"',
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def render_cursor_json(servers: list[MCPClientServer]) -> str:
    payload = {
        "mcpServers": {
            server.server_name: {
                "url": server.url,
                "connection_id": server.server_name.replace("-", "_"),
            }
            for server in servers
        }
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def _server_name_for_project(project: str) -> str:
    slug = re.sub(r"[^a-z0-9_-]+", "-", project.lower())
    slug = re.sub(r"-{2,}", "-", slug).strip("-_")
    if not slug:
        slug = "project"
    return f"{SERVER_NAME_PREFIX}-{slug}"


def _dedupe_names(names: list[str]) -> list[str]:
    seen: dict[str, int] = {}
    result: list[str] = []
    for name in names:
        count = seen.get(name, 0)
        seen[name] = count + 1
        if count == 0:
            result.append(name)
        else:
            result.append(f"{name}-{count + 1}")
    return result


def _toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
